name: main
on:
  push:
    tags: '*'
jobs:
  main:
    runs-on: windows-2022
    steps:
    - name: install
      shell: cmd
      run: |
        set PATH=C:\Miniconda;C:\Miniconda\Scripts;%PATH%
        pip install aqtinstall
        mkdir Qt
        pushd Qt
          aqt install-tool windows desktop tools_vcredist qt.tools.vcredist_msvc2019_x86
        popd
        7z a vcredist_msvc2019_x86.7z Qt
        rmdir /q /s Qt
        mkdir Qt
        pushd Qt
          aqt install-tool windows desktop tools_vcredist qt.tools.vcredist_msvc2019_x64
        popd
        7z a vcredist_msvc2019_x64.7z Qt
        rmdir /q /s Qt
    - uses: ncipollo/release-action@v1
      if: startsWith( github.ref, 'refs/tags/')
      with:
        artifacts: |
          vcredist_msvc2019_x86.7z
          vcredist_msvc2019_x64.7z
        token: ${{ secrets.GITHUB_TOKEN }}
