name: main
on: [push]
jobs:
  main:
    runs-on: windows-2022
    steps:
    - name: install
      shell: cmd
      run: |
        set PATH=C:\Miniconda;C:\Miniconda\Scripts;%PATH%
        pip install aqtinstall
        mkdir Qt
        pushd Qt
          aqt install-qt windows desktop 5.15.2 win64_mingw81
        popd
        7z a 5.15.2.7z Qt
        rmdir /q /s Qt
        mkdir Qt
        pushd Qt
          aqt install-doc windows 5.15.2
        popd
        7z a Docs.7z Qt
        rmdir /q /s Qt
        mkdir Qt
        pushd Qt
          aqt install-tool windows desktop tools_mingw qt.tools.win64_mingw810
        popd
        7z a mingw810.7z Qt        
    - uses: ncipollo/release-action@v1
      if: startsWith( github.ref, 'refs/tags/')
      with:
        artifacts: |
          5.15.2.7z
          Docs.7z
          mingw810.7z
        token: ${{ secrets.GITHUB_TOKEN }}
