name: main
on: [push]
jobs:
  main:
    runs-on: windows-2022
    steps:
    - name: install
      shell: cmd
      run: |
        set PATH=C:\Miniconda;C:\Miniconda\Scripts;%PATH%
        pip install aqtinstall
        aqt install-qt windows desktop 5.15.2 win64_mingw81 -O C:\Qt
        7z a -mx1 5.15.2.7z C:\Qt
        rmdir /q /s C:\Qt
        aqt install-doc windows 5.15.2 -O C:\Qt
        7z a -mx1 5.15.2-Docs.7z C:\Qt
        rmdir /q /s C:\Qt
        aqt install-tool windows desktop tools_mingw qt.tools.win64_mingw810 -O C:\Qt
        7z a -mx1 mingw810.7z C:\Qt
    - name: release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: |
          5.15.2.7z
          5.15.2-Docs.7z
          mingw810.7z

