name: main
on: [push]
jobs:
  main:
    runs-on: windows-2022
    steps:
    - name: install
      shell: cmd
      run: |
        set PATH=C:\Miniconda;C:\Miniconda\Scripts;%PATH%
        pip install aqtinstall
        mkdir Qt
        pushd Qt
          aqt install-qt windows desktop 6.3.0 win64_mingw --archives qtbase qtserialport qtsvg
        popd
        7z a 6.3.0.7z Qt
    - uses: ncipollo/release-action@v1
      if: startsWith( github.ref, 'refs/tags/')
      with:
        artifacts: 6.3.0.7z
        token: ${{ secrets.GITHUB_TOKEN }}
