name: main
on: [push]
jobs:
  main:
    runs-on: windows-2022
    steps:
    - name: install
      shell: cmd
      run: |
        set PATH=C:\Miniconda;C:\Miniconda\Scripts;%PATH%
        pip install aqtinstall
        mkdir Qt
        pushd Qt
          aqt install-qt windows desktop 5.11.3 win32_mingw53 --archives qtbase qtserialport qtsvg
        popd
        7z a 5.11.3.7z Qt
        rmdir /q /s Qt
        mkdir Qt
        pushd Qt
          aqt install-tool windows desktop tools_mingw qt.tools.win32_mingw530
        popd
        7z a mingw530_32.7z Qt
        rmdir /q /s Qt
        mkdir Qt
        pushd Qt
          aqt install-tool windows desktop tools_qtcreator qt.tools.qtcreator
        popd
        7z a QtCreator.7z Qt
    - uses: ncipollo/release-action@v1
      if: startsWith( github.ref, 'refs/tags/')
      with:
        artifacts: |
          5.11.3.7z
          mingw530_32.7z
          QtCreator.7z
        token: ${{ secrets.GITHUB_TOKEN }}
